### ISSUE TITLE
Checking address balance method

### ISSUE THREAD

**Issue by huggre** [vessels-tech/arduino_iota_client#1]
Hi Lewis

I'm currently writing a series of tutorials on integrating devices with the IOTA protocol.
Your idea on having a lightweight IOTA C library running on a ESP8266 is quite intriguing as it would open for a lot of new use-cases running on low-cost hardware. In my use-case i basically just need to check the current balance for a particular IOTA address. Do you have any plans on implementing this method (or if it would be possible) in your library?

Hugo

**Comment by lewisdaly** [comment]
Hi Hugo,

Thanks for reaching out to me.

Getting IOTA running on low cost hardware is for sure a goal of mine. My library is just a fork of the original IOTA lightweight C library, which is in turn a fork of the ledger nano c library. I’m sure it would be possible, the challenge I forsee is getting the HTTP requests signed and working, as well as iterating through all used addresses for a seed (this number could be quite large) without running out of memory. I’d love to have the time to work on this, but I don’t think I’ll get to it for a while!

Cheers,
Lewis
